GET http://localhost:3003/accounts

---
POST http://localhost:3003/accounts/create
Content-Type: application/json

{
  "name": "Fulano",
  "cpf": "1234567890",
  "email": "gazua@email.com",
  "password": "senha",
  "passwordConf": "senha",
  "initialDate": "04/06/1999"
}

---
POST http://localhost:3003/accounts/balance
Content-Type: application/json

{
  "name": "Vanires",
  "cpf": "1234567892"
}

---
POST http://localhost:3003/accounts/statement
Content-Type: application/json

{
  "name": "Vanires",
  "cpf": "1234567892"
}

---
POST http://localhost:3003/accounts/payment
Content-Type: application/json

{
  "name": "Flamarion",
  "cpf": "1234567891",
  "initialDate": "10/12/2022",
  "value": 80,
  "description": "pagamento de prestação de cartão de crédito"
}

---
POST http://localhost:3003/accounts/deposit
Content-Type: application/json

{
  "name": "Vanires",
  "cpf": "1234567892",
  "value": 80
}

---
POST http://localhost:3003/accounts/login
Content-Type: application/json

{
  "cpf": 1234567892,
  "password": "senha"
}

---
POST http://localhost:3003/accounts/transfer
Content-Type: application/json

{
  "name":"Flamarion",
  "cpf": 1234567891,
  "recipientName": "Vanires",
  "recipientCpf": 1234567892,
  "value": 100
}
